image:
  file: .gitpod.Dockerfile

ports:
  # Laravel server
  - port: 8000
    onOpen: open-preview
  # MySQL server
  - port: 3306
    onOpen: ignore

tasks:
  - init: >
      mysql -u root -e "create database snipeit" &&
      cp .env.gitpod.example .env &&
      sed -i "s|APP_URL=|APP_URL=${GITPOD_WORKSPACE_URL}|g" .env &&
      sed -i "s|APP_URL=https://|APP_URL=https://8000-|g" .env &&
      composer install &&
      npm i &&
      php artisan migrate --force

      php artisan key:generate
    command: >
      php -S 0.0.0.0:8000 -t public
